"""The configuration half of the one-command installers (scripts/install.sh, install.ps1).

The shell scripts fetch the code and build the virtualenv; this module does
everything that needs Python, the same way on every OS:

1. detect the OS, memory and GPU (:mod:`auto_router.hardware`), the installed
   harnesses (:mod:`auto_router.harness`), API keys **by variable name only**,
   and local model servers already running (LM Studio, llama.cpp, Ollama);
2. ask - or take from flags - which model groups and harnesses to set up;
3. write ``~/.auto-router/config.yaml`` (HTTP router) and ``launcher.yaml``
   (route-run and the delegate tool), keys referenced by name;
4. optionally fetch a local model (``--with-bonsai``, ``--with-jev-local``),
   only after showing its size and getting a yes;
5. configure the chosen harnesses, each edit backed up and undoable.

    python -m auto_router.installer --yes --models cloud,jev-local --harness opencode,codex
    python -m auto_router.installer --dry-run --models cloud --harness all
    python -m auto_router.installer --uninstall

It never prints, stores or writes a key value.
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import shutil
import subprocess
import sys
import time
import urllib.request
from pathlib import Path
from typing import Any, Callable

from . import hardware, harness

GROUPS = ("cloud", "subscription", "bonsai", "jev-local")
KEY_NAMES = ("OPENROUTER_API_KEY", "TENSORX_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY",
             "TYPESAFE_API_KEY")
LOCAL_PORTS = {1234: "LM Studio", 8080: "llama.cpp llama-server", 8081: "llama-server (Bonsai, this installer)",
               8082: "llama-server (Jev-class, this installer)", 11434: "Ollama"}
GENERATED = "# Generated by the auto-router installer"


# ----------------------------------------------------------------- detection

def key_names(env: dict[str, str]) -> dict[str, bool]:
    """Which known key variables are set. Names only; values are never read out."""
    return {name: bool(env.get(name)) for name in KEY_NAMES}


def probe_local(ports: dict[int, str] = LOCAL_PORTS, timeout: float = 1.5,
                fetch: Callable[[str, float], Any] | None = None) -> list[dict]:
    """OpenAI-compatible servers answering on loopback, with the model ids they list."""
    def _fetch(url: str, t: float) -> Any:
        with urllib.request.urlopen(url, timeout=t) as resp:  # noqa: S310 - loopback only
            return json.load(resp)
    fetch = fetch or _fetch
    found = []
    for port, label in ports.items():
        url = f"http://127.0.0.1:{port}/v1"
        try:
            data = fetch(url + "/models", timeout)
        except Exception:
            continue
        ids = [str(m.get("id")) for m in (data.get("data") or []) if isinstance(m, dict)]
        found.append({"url": url, "port": port, "label": label, "models": ids})
    return found


def match_endpoint(endpoints: list[dict], words: tuple[str, ...]) -> tuple[str, str] | None:
    for ep in endpoints:
        for mid in ep["models"]:
            if any(w in mid.lower() for w in words):
                return ep["url"], mid
    return None


# ----------------------------------------------------------- config writing

CLOUD_MODELS = [
    # name, openrouter id, bench id, tensorx id, direct-openai id
    ("glm-5.3-flash", "z-ai/glm-5.3-flash", "glm-5.3-flash::default", "z-ai/glm-5.3-flash", None),
    ("gpt-6-luna", "openai/gpt-6-luna", "gpt-6-luna::medium", None, "gpt-6-luna"),
    ("claude-sonnet-5", "anthropic/claude-sonnet-5", "claude-sonnet-5::medium", None, None),
    ("gpt-6-astra", "openai/gpt-6-astra", "gpt-6-astra::medium", None, "gpt-6-astra"),
    ("claude-opus-5.5", "anthropic/claude-opus-5.5", "claude-opus-5.5::medium", None, None),
]


def render_config(*, groups: list[str], keys: dict[str, bool], src: str,
                  bonsai: dict | None, jev: dict | None, classifier: str) -> str:
    """The router config as commented YAML. Keys appear only as variable names."""
    L: list[str] = [
        f"{GENERATED} on {time.strftime('%Y-%m-%d')}. Edit freely; rerunning the",
        "# installer keeps an edited file and writes config.yaml.new next to it.",
        "#",
        "# Keys are referenced by environment variable NAME only. To use fewer models,",
        "# edit `enabled` below or set AUTO_ROUTER_MODELS=a,b,c without editing this file.",
        "",
        "providers:",
    ]
    models: list[str] = []
    enabled: list[str] = []
    if "cloud" in groups:
        L += ["  openrouter:", "    base_url: https://openrouter.ai/api/v1",
              "    api_key_env: OPENROUTER_API_KEY", "    cache: openai",
              "  tensorx:", "    base_url: https://api.tensorx.ai/v1",
              "    api_key_env: TENSORX_API_KEY", "    cache: openai"]
        if keys.get("OPENAI_API_KEY"):
            L += ["  openai:", "    base_url: https://api.openai.com/v1",
                  "    api_key_env: OPENAI_API_KEY", "    cache: openai"]
        for name, or_id, bench_id, tx_id, oa_id in CLOUD_MODELS:
            vendor = "Anthropic" if "claude" in name else ("OpenAI" if "gpt" in name else None)
            offer = "{platform: OpenRouter" + (f", provider: {vendor}}}" if vendor else "}")
            models += [f"  - name: {name}", "    provider: openrouter", f"    upstream_id: {or_id}",
                       f"    bench_id: {bench_id}", f"    bench_offer: {offer}"]
            if "claude" in name:
                models += ["    cache_family: anthropic", "    vision: true"]
            if keys.get("OPENROUTER_API_KEY"):
                enabled.append(name)
            if tx_id:
                models += [f"  - name: {name}-tensorx", "    provider: tensorx", f"    upstream_id: {tx_id}",
                           f"    bench_id: {bench_id}", "    bench_offer: {platform: TensorX}"]
                if keys.get("TENSORX_API_KEY"):
                    enabled.append(f"{name}-tensorx")
            if oa_id and keys.get("OPENAI_API_KEY"):
                models += [f"  - name: {name}-openai", "    provider: openai", f"    upstream_id: {oa_id}",
                           f"    bench_id: {bench_id}", "    bench_offer: {platform: OpenRouter, provider: OpenAI}"]
                enabled.append(f"{name}-openai")
    if "subscription" in groups:
        L += ["  anthropic:", "    base_url: https://api.anthropic.com/v1", "    api: anthropic",
              "    cache: anthropic"]
        models += ["  # Your Claude plan. Reached in switch mode (`auto-router switch`), where Claude",
                   "  # Code talks to Anthropic directly with your own login; the router never sees it.",
                   "  - name: claude-plan", "    provider: anthropic", "    upstream_id: claude-opus-5.5",
                   "    bench_id: claude-opus-5.5::medium",
                   "    bench_offer: {platform: OpenRouter, provider: Anthropic}",
                   "    subscription: claude", "    list_price_model: claude-opus-5.5",
                   "    cache_family: anthropic", "    vision: true"]
        enabled.append("claude-plan")
    if bonsai:
        L += ["  local-bonsai:", f"    base_url: {bonsai['url']}", "    local: true"]
        models += ["  # Bonsai 2 (Ternary-Bonsai-2-27B, Apache-2.0) on this machine. Its capability is",
                   "  # ASSUMED equal to its base model (capability_like); not measured here.",
                   "  - name: bonsai-2-27b", "    provider: local-bonsai", f"    upstream_id: {bonsai['model']}",
                   "    free: true", "    capability_like: qwen3.8-27b::medium", "    context_tokens: 32768"]
        enabled.append("bonsai-2-27b")
    if len(L) == 7:
        L[-1] = "providers: {}"
    L += ["", "subscriptions:" if "subscription" in groups else "subscriptions: {}"]
    if "subscription" in groups:
        L += ["  claude:",
              "    # Opens for automatic switching only once usage_command reports how full the",
              "    # plan is. Until then start a prompt with ~plan to send it to the plan yourself.",
              "    # usage_command: [/path/to/your/usage-reader, --json]",
              "    weekly_reserve: 0.65", "    hard_stop: 0.80"]
    L += ["", "policy:", "  name: F_expected", "  escalate_after_tool_errors: 3",
          "  jev_difficulty_calibration: [0.27, 0.51]", "  success:",
          f"    table: {src}/examples/success.measured.json", "  classifier:"]
    if classifier == "jev-local" and jev:
        L += ["    # A local open Jev-class decision model (Apache-2.0) over an OpenAI-compatible",
              "    # endpoint. Nothing leaves this machine.",
              "    backend: local-jev", f"    base_url: {jev['url']}", f"    model: {jev['model']}"]
        if jev.get("temperature"):
            L.append(f"    temperature: {jev['temperature']}")
    elif classifier == "hosted":
        L += ["    backend: hosted   # TypeSafe Jev with your own TYPESAFE_API_KEY (BYOK)"]
    elif classifier == "laya":
        L += ["    backend: local    # Laya on the CPU (pip extra [local])",
              "    model: convaiinnovations/laya", "    threads: 4"]
    else:
        L += ["    backend: heuristic   # no classifier model; set up jev-local or TYPESAFE_API_KEY for better routing"]
    L += ["", "models:"] + (models or ["  []"])
    if enabled:
        L += ["", "# Only these routes are used. The installer listed the models whose key variable",
              "# was set when it ran, plus local ones; add names when you add keys.",
              "enabled: [" + ", ".join(enabled) + "]"]
    return "\n".join(L).replace("models:\n  []", "models: []") + "\n"


def render_launcher(*, groups: list[str], src: str, detected: dict[str, dict]) -> str:
    """route-run / delegate config: which official CLI runs a whole job."""
    have = {h for h, info in detected.items() if info.get("installed")}
    L = [f"{GENERATED} on {time.strftime('%Y-%m-%d')}.",
         "# Job-level routing (`auto-router run`) and the delegate MCP tool read this file.",
         "# Each route starts an official CLI, unmodified. Keys by variable name only.",
         "", "providers:", "  openrouter:", "    base_url: https://openrouter.ai/api/v1",
         "    api_key_env: OPENROUTER_API_KEY", "    cache: openai",
         "  anthropic:", "    base_url: https://api.anthropic.com/v1", "    api: anthropic", "    cache: anthropic",
         "  openai:", "    base_url: https://api.openai.com/v1", "    cache: openai", ""]
    subs = []
    if "subscription" in groups:
        subs = ["subscriptions:", "  codex:", "    codex_rollouts: ~/.codex/sessions", "    weekly_reserve: 0.65",
                "    hard_stop: 0.80", "    clear_env: [OPENAI_API_KEY]", "  claude:",
                "    # usage_command: [my-claude-usage, --json]   # closed until set",
                "    weekly_reserve: 0.65", "    hard_stop: 0.80",
                "    clear_env: [ANTHROPIC_API_KEY, ANTHROPIC_AUTH_TOKEN]", ""]
    L += subs + ["policy:", "  name: F_expected", "  jev_difficulty_calibration: [0.27, 0.51]",
                 "  success:", f"    table: {src}/examples/success.measured.json", "", "models:",
                 "  - name: glm-5.3-flash", "    provider: openrouter", "    upstream_id: z-ai/glm-5.3-flash",
                 "    bench_id: glm-5.3-flash::default", "    bench_offer: {platform: OpenRouter}",
                 "    runner:", "      cmd: [opencode, run, -m, openrouter/z-ai/glm-5.3-flash, \"{task}\"]",
                 "      env_pass: [OPENROUTER_API_KEY]", "      timeout_s: 1800",
                 "  - name: gpt-6-astra-metered", "    provider: openrouter", "    upstream_id: openai/gpt-6-astra",
                 "    bench_id: gpt-6-astra::medium", "    bench_offer: {platform: OpenRouter, provider: OpenAI}",
                 "    runner:", "      cmd: [opencode, run, -m, openrouter/openai/gpt-6-astra, \"{task}\"]",
                 "      env_pass: [OPENROUTER_API_KEY]", "      timeout_s: 3600"]
    if "subscription" in groups:
        L += ["  # Your ChatGPT plan through the Codex CLI. Launch-only: never served over HTTP.",
              "  - name: codex-plan", "    provider: openai", "    upstream_id: gpt-6-astra",
              "    bench_id: gpt-6-astra::medium", "    bench_offer: {platform: OpenRouter, provider: OpenAI}",
              "    subscription: codex", "    launch_only: true", "    list_price_model: gpt-6-astra-metered",
              "    runner:", "      cmd: [codex, exec, \"{task}\"]", "      clear_env: [OPENAI_API_KEY]",
              "      timeout_s: 3600",
              "  # Your Claude plan through Claude Code. Closed until usage_command is set.",
              "  - name: claude-plan", "    provider: anthropic", "    upstream_id: claude-opus-5.5",
              "    bench_id: claude-opus-5.5::medium", "    bench_offer: {platform: OpenRouter, provider: Anthropic}",
              "    subscription: claude", "    launch_only: true", "    list_price_model: gpt-6-astra-metered",
              "    cache_family: anthropic", "    runner:",
              "      cmd: [claude, -p, --model, opus, --permission-mode, acceptEdits]", "      stdin: true",
              "      clear_env: [ANTHROPIC_API_KEY, ANTHROPIC_AUTH_TOKEN]", "      timeout_s: 3600"]
    missing = [c for c in ("opencode", "codex", "claude-code") if c not in have]
    if missing:
        L += ["", f"# Not detected when this was written: {', '.join(missing)}. Routes whose CLI is",
              "# missing fail when chosen; remove them or install the CLI."]
    return "\n".join(L) + "\n"


def write_config(path: Path, text: str, *, dry_run: bool, say: Callable[[str], None]) -> Path | None:
    """Write ``text``; keep a hand-edited file and put the new one beside it."""
    try:
        import yaml
        yaml.safe_load(text)                    # never write a file that does not parse
    except ModuleNotFoundError:
        if not dry_run:
            raise
    if dry_run:
        say(f"[dry-run] would write {path}")
        return None
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        old = path.read_text(encoding="utf-8")
        if old == text:
            say(f"{path} unchanged")
            return path
        if not old.startswith(GENERATED):
            new = path.with_name(path.name + ".new")
            new.write_text(text, encoding="utf-8")
            say(f"kept your {path}; the installer's version is {new}")
            return new
        backup = path.with_name(f"{path.name}.auto-router-bak-{time.strftime('%Y%m%dT%H%M%S')}")
        shutil.copy2(path, backup)
        say(f"replaced {path} (it was generated by an earlier run; backup {backup.name})")
    path.write_text(text, encoding="utf-8")
    say(f"wrote {path}")
    return path


def validate_router_config(path: Path) -> str | None:
    """Check the written config against the installed router: the error text, or None.

    Parses the YAML, builds the classifier the policy names (an unknown backend
    raises), and checks every model can get a price. Model prices themselves
    come from the benchmark API when the router starts, so they are not fetched here.
    """
    try:
        import yaml
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        from . import jev
        jev.classifier_from_config(raw.get("policy") or {})
        providers = raw.get("providers") or {}
        for m in raw.get("models") or []:
            if m.get("provider") not in providers:
                return f"model {m.get('name')!r} names an unknown provider {m.get('provider')!r}"
            if not (m.get("bench_id") or m.get("prices") or m.get("free") or m.get("subscription")
                    or m.get("capability_like")):
                return f"model {m.get('name')!r} has no price source"
    except Exception as exc:  # the config must not ship broken; report the reason
        return f"{type(exc).__name__}: {exc}"
    return None


# -------------------------------------------------------------- local models

def human_gb(n: float) -> str:
    return f"{n:.2f} GB"


def download(repo: str, file: str, dest: Path, *, run=subprocess.run, which=shutil.which,
             say: Callable[[str], None] = print) -> Path:
    """Fetch one file from Hugging Face: the hf CLI if present, else curl, else urllib."""
    dest.mkdir(parents=True, exist_ok=True)
    target = dest / file
    if target.exists():
        say(f"{target} already present")
        return target
    free = shutil.disk_usage(dest).free
    say(f"free disk at {dest}: {human_gb(free / 1e9)}")
    url = f"https://huggingface.co/{repo}/resolve/main/{file}"
    hf = which("hf") or which("huggingface-cli")
    if hf:
        run([hf, "download", repo, file, "--local-dir", str(dest)], check=True)
    elif which("curl"):
        run(["curl", "-fL", "-C", "-", "-o", str(target) + ".part", url], check=True)
        os.replace(str(target) + ".part", target)
    else:
        urllib.request.urlretrieve(url, str(target) + ".part")  # noqa: S310 - fixed https host
        os.replace(str(target) + ".part", target)
    return target


def write_start_script(state: Path, name: str, command: str, os_name: str, note: str,
                       *, dry_run: bool, say: Callable[[str], None]) -> Path:
    bin_dir = state / "bin"
    if os_name == "windows":
        path = bin_dir / f"start-{name}.cmd"
        text = f"@echo off\r\nrem {note}\r\n{command}\r\n"
    else:
        path = bin_dir / f"start-{name}"
        text = f"#!/bin/sh\n# {note}\nexec {command}\n"
    if dry_run:
        say(f"[dry-run] would write {path}: {command}")
        return path
    bin_dir.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    if os_name != "windows":
        path.chmod(0o755)
    say(f"wrote {path}")
    return path


# ------------------------------------------------------------------ prompts

class Asker:
    def __init__(self, interactive: bool, yes: bool, stream=None):
        self.interactive, self.yes, self.stream = interactive, yes, stream

    def _input(self, prompt: str) -> str:
        if self.stream is not None:
            print(prompt, end="", flush=True)
            return self.stream.readline().strip()
        return input(prompt).strip()

    def confirm(self, question: str, default: bool = False) -> bool:
        if self.yes:
            return True
        if not self.interactive:
            return default
        ans = self._input(f"{question} [{'Y/n' if default else 'y/N'}] ").lower()
        return default if not ans else ans.startswith("y")

    def choose(self, question: str, options: list[str], default: list[str]) -> list[str]:
        if not self.interactive:
            return default
        ans = self._input(f"{question}\n  options: {', '.join(options)}\n  [{','.join(default) or 'none'}] ")
        if not ans:
            return default
        if ans.strip().lower() == "none":
            return []
        return [x.strip() for x in ans.split(",") if x.strip() in options or x.strip() == "all"]


# --------------------------------------------------------------------- main

def plan(args: argparse.Namespace, *, env: dict[str, str], hw_rec: dict, found: dict,
         endpoints: list[dict], asker: Asker, say: Callable[[str], None]) -> dict:
    """Decide groups, harnesses, classifier and local endpoints from flags or answers."""
    keys = key_names(env)
    groups = _split(args.models, GROUPS)
    if groups is None:
        default = ["cloud"] + (["jev-local"] if match_endpoint(endpoints, ("jev", "decider")) else [])
        say("Model groups: cloud = API models on your own keys; subscription = your Claude / ChatGPT "
            "plan through its own CLI (switch mode, route-run, MCP tool); bonsai = Bonsai 2 on this "
            "machine; jev-local = a local open Jev-class decision model for routing.")
        groups = asker.choose("Which model groups?", list(GROUPS), default)
    detected = [h for h, i in found.items() if i["installed"]]
    harnesses = _split(args.harness, harness.HARNESSES)
    if harnesses is None:
        harnesses = asker.choose("Configure which harnesses? (detected ones preselected)",
                                 list(harness.HARNESSES), detected if (asker.interactive or asker.yes) else [])
    gateway = bool(args.claude_gateway)
    if "claude-code" in harnesses and "subscription" in groups and not gateway and asker.interactive:
        gateway = asker.confirm(
            "Also route Claude Code through the local gateway with your own claude.ai login "
            "(ANTHROPIC_BASE_URL)? Own login, own machine only; Anthropic does not support "
            "routing Claude Code to non-Claude models. Switch mode + MCP tool are the default.", False)

    bonsai = jev = None
    if "bonsai" in groups:
        hit = match_endpoint(endpoints, ("bonsai",))
        if hit:
            bonsai = {"url": hit[0], "model": hit[1], "source": "running endpoint"}
    if "jev-local" in groups:
        hit = match_endpoint(endpoints, ("jev", "decider"))
        if hit:
            jev = {"url": hit[0], "model": hit[1], "source": "running endpoint"}
    classifier = args.classifier
    if classifier == "auto":
        classifier = ("jev-local" if "jev-local" in groups else
                      "hosted" if keys.get("TYPESAFE_API_KEY") else "heuristic")
    return {"groups": groups, "harnesses": harnesses, "claude_gateway": gateway, "keys": keys,
            "bonsai": bonsai, "jev": jev, "classifier": classifier}


def _split(value: str | None, allowed: tuple[str, ...]) -> list[str] | None:
    if value is None:
        return None
    items = [x.strip() for x in value.split(",") if x.strip()]
    if items == ["all"]:
        return list(allowed)
    if items == ["none"]:
        return []
    bad = [x for x in items if x not in allowed]
    if bad:
        raise SystemExit(f"unknown value(s) {', '.join(bad)}; choose from {', '.join(allowed)}")
    return items


def fetch_local(kind: str, rec: dict, p: dict, args, asker: Asker, state: Path, os_name: str,
                say: Callable[[str], None]) -> None:
    """--with-bonsai / --with-jev-local: download after a yes, write a start script."""
    if kind == "bonsai":
        pick = rec["bonsai"]
        if not pick.get("fits"):
            say(f"Bonsai 2: not downloaded - {pick['reason']}")
            return
        repo, file, gb, port = pick["repo"], pick["file"], pick["gb"], 8081
        extra = ("Needs the PrismML llama.cpp fork: https://github.com/PrismML-Eng/llama.cpp/releases "
                 "(stock llama.cpp will not load this file).")
        server = "llama-server"
        tail = "-ngl 99 -fa on -c 32768 --temp 1.0 --top-p 0.95 --top-k 20 --min-p 0.05"
    else:
        pick = rec["jev"]
        if not pick.get("id") or not str(pick.get("file", "")).endswith(".gguf"):
            say(f"Jev-class model: nothing to download for this machine ({pick.get('display') or pick.get('reason')}). "
                "Use `--classifier laya` for the in-process Laya fallback.")
            return
        repo, file, gb, port = pick["repo"], pick["file"], pick["gb"], 8082
        extra = "Any recent llama.cpp llama-server works (https://github.com/ggml-org/llama.cpp/releases)."
        server = "llama-server"
        tail = "-c 8192" + (" -ngl 99" if pick["device"] != "cpu" else "")
    say(f"{kind}: {file} from huggingface.co/{repo} is {human_gb(gb)} ({pick.get('licence')}). {extra}")
    if not asker.confirm(f"Download {human_gb(gb)} now?", False):
        say(f"{kind}: not downloaded (confirm interactively or pass --yes)")
        return
    dest = state / "models"
    if args.dry_run:
        say(f"[dry-run] would download {file} to {dest}")
    else:
        download(repo, file, dest, say=say)
    cmd = f"{server} -m \"{dest / file}\" --host 127.0.0.1 --port {port} {tail}"
    write_start_script(state, kind, cmd, os_name, extra, dry_run=args.dry_run, say=say)
    entry = {"url": f"http://127.0.0.1:{port}/v1", "model": file.removesuffix(".gguf"), "source": "downloaded"}
    if kind == "jev-local" and pick.get("id", "").startswith("jevk5-v0.2"):
        entry["temperature"] = 1.532
    p["bonsai" if kind == "bonsai" else "jev"] = entry


def run_install(args: argparse.Namespace, *, env: dict[str, str] | None = None,
                asker: Asker | None = None, endpoints: list[dict] | None = None,
                hw: hardware.Hardware | None = None, which=shutil.which) -> dict:
    env = dict(os.environ if env is None else env)
    lines: list[str] = []

    def say(s: str) -> None:
        lines.append(s)
        if not args.json:
            print(f"  {s}", flush=True)

    ctx = harness.Ctx.from_env(dry_run=args.dry_run, force=args.force, router_url=args.router_url,
                               launcher=args.launcher or "",
                               project=Path(args.project).resolve() if args.project else None,
                               delegate=not args.no_delegate)
    ctx.env, ctx.which = env, which
    if args.home:
        ctx.home = Path(args.home)
        ctx.state_dir = Path(args.state_dir) if args.state_dir else ctx.home / ".auto-router"
    elif args.state_dir:
        ctx.state_dir = Path(args.state_dir)
    if not args.launcher:
        ctx.launcher = ""
        ctx.__post_init__()
    if ctx.os_name == "windows" and not args.no_delegate:
        ctx.delegate = False
        say("Windows: the MCP delegate tool and route-run need POSIX process control; use WSL "
            "for them. The HTTP router and harness provider entries are set up here.")
    state = ctx.state_dir
    src = args.src or str(state / "src")
    asker = asker or Asker(interactive=sys.stdin.isatty() and not args.yes, yes=args.yes)

    hw = hw or hardware.detect()
    rec = hardware.recommend(hw, with_bonsai=True)
    found = harness.detect(ctx, which)
    endpoints = probe_local() if endpoints is None else endpoints
    say(f"system: {hw.os}{' (WSL)' if hw.wsl else ''}, {hw.arch}, RAM {hw.ram_gb} GB, GPU: "
        + (", ".join(f"{g.name} {g.vram_gb} GB" for g in hw.gpus) or "none detected"))
    say("harnesses found: " + (", ".join(h for h, i in found.items() if i["installed"]) or "none"))
    keys = key_names(env)
    say("key variables set: " + (", ".join(k for k, v in keys.items() if v) or "none")
        + "; not set: " + (", ".join(k for k, v in keys.items() if not v) or "none"))
    say("local model servers: " + (", ".join(f"{e['label']} at {e['url']} ({len(e['models'])} models)"
                                             for e in endpoints) or "none running"))

    p = plan(args, env=env, hw_rec=rec, found=found, endpoints=endpoints, asker=asker, say=say)
    say(f"model groups: {', '.join(p['groups']) or 'none'}; harnesses: {', '.join(p['harnesses']) or 'none'}")

    if "bonsai" in p["groups"] and not p["bonsai"]:
        if args.with_bonsai:
            fetch_local("bonsai", rec, p, args, asker, state, ctx.os_name, say)
        else:
            say(f"Bonsai 2: no running endpoint found. {'Fits' if rec['bonsai']['fits'] else 'Does not fit'}: "
                f"{rec['bonsai']['reason']}. Rerun with --with-bonsai to download it, or serve it in LM "
                "Studio / llama-server and rerun.")
    if "jev-local" in p["groups"] and not p["jev"]:
        if args.with_jev_local:
            fetch_local("jev-local", rec, p, args, asker, state, ctx.os_name, say)
        else:
            say(f"Jev-class model: no running endpoint found; picked for this machine: "
                f"{rec['jev'].get('display')} ({rec['jev'].get('device')}). Rerun with --with-jev-local "
                "to download it, or serve it yourself and rerun.")
    if p["classifier"] == "jev-local" and not p["jev"]:
        p["classifier"] = "hosted" if keys.get("TYPESAFE_API_KEY") else "heuristic"
        say(f"classifier: {p['classifier']} until a local Jev-class endpoint is configured")

    config_text = render_config(groups=p["groups"], keys=keys, src=src, bonsai=p["bonsai"], jev=p["jev"],
                                classifier=p["classifier"])
    cfg_path = write_config(state / "config.yaml", config_text, dry_run=args.dry_run, say=say)
    if cfg_path and not args.no_validate:
        err = validate_router_config(cfg_path)
        if err and p["classifier"] == "jev-local":
            say(f"this router version does not accept the local-jev classifier ({err}); "
                "falling back to the heuristic classifier")
            p["classifier"] = "heuristic"
            config_text = render_config(groups=p["groups"], keys=keys, src=src, bonsai=p["bonsai"],
                                        jev=p["jev"], classifier="heuristic")
            cfg_path = write_config(cfg_path, config_text, dry_run=False, say=say)
            err = validate_router_config(cfg_path)
        if err:
            say(f"WARNING: the router could not load {cfg_path}: {err}. Edit it before starting the router.")
    write_config(state / "launcher.yaml", render_launcher(groups=p["groups"], src=src, detected=found),
                 dry_run=args.dry_run, say=say)

    ctx.claude_gateway = p["claude_gateway"]
    results = harness.configure(ctx, p["harnesses"]) if p["harnesses"] else {}
    for line in ctx.log:
        say(line)
    summary = {"groups": p["groups"], "harnesses": results, "classifier": p["classifier"],
               "bonsai": p["bonsai"], "jev": p["jev"], "claude_gateway": p["claude_gateway"],
               "keys_set": [k for k, v in keys.items() if v], "config": str(state / "config.yaml"),
               "hardware": rec, "dry_run": args.dry_run, "log": lines}
    if not args.dry_run:
        (state / "install-summary.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    return summary


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Configure the auto router and your coding harnesses.")
    p.add_argument("--yes", "-y", action="store_true", help="no questions; accept downloads you asked for")
    p.add_argument("--models", help=f"comma list of {', '.join(GROUPS)} (or all / none)")
    p.add_argument("--harness", help=f"comma list of {', '.join(harness.HARNESSES)} (or all / none)")
    p.add_argument("--classifier", default="auto", choices=("auto", "jev-local", "hosted", "heuristic", "laya"))
    p.add_argument("--with-bonsai", action="store_true", help="download Bonsai 2 if no endpoint runs (asks first)")
    p.add_argument("--with-jev-local", action="store_true",
                   help="download the picked Jev-class model if no endpoint runs (asks first)")
    p.add_argument("--claude-gateway", action="store_true",
                   help="opt-in: ANTHROPIC_BASE_URL -> local router for Claude Code (own login, own machine)")
    p.add_argument("--project", help="Cursor: project directory for the rule file")
    p.add_argument("--no-delegate", action="store_true", help="skip the MCP delegate tool")
    p.add_argument("--router-url", default="http://127.0.0.1:8787")
    p.add_argument("--launcher", help="path of the auto-router launcher command")
    p.add_argument("--src", help="router source checkout (default ~/.auto-router/src)")
    p.add_argument("--home", help=argparse.SUPPRESS)
    p.add_argument("--state-dir", help=argparse.SUPPRESS)
    p.add_argument("--force", action="store_true", help="replace differing entries (after a backup)")
    p.add_argument("--dry-run", action="store_true", help="print what would change; change nothing")
    p.add_argument("--no-validate", action="store_true", help=argparse.SUPPRESS)
    p.add_argument("--uninstall", action="store_true", help="undo every harness edit this installer made")
    p.add_argument("--json", action="store_true", help="print a JSON summary instead of text")
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.uninstall:
        ctx = harness.Ctx.from_env(dry_run=args.dry_run)
        if args.home:
            ctx.home = Path(args.home)
            ctx.state_dir = Path(args.state_dir) if args.state_dir else ctx.home / ".auto-router"
        lines = harness.undo(ctx)
        print(json.dumps({"undone": lines}, indent=2) if args.json else
              "\n".join(f"  {l}" for l in lines) or "  nothing to undo")
        return 0
    summary = run_install(args)
    if args.json:
        print(json.dumps({k: v for k, v in summary.items() if k != "log"} | {"log": summary["log"]}, indent=2))
    refused = [h for h, r in summary["harnesses"].items() if isinstance(r, str) and r.startswith("refused")]
    return 3 if refused else 0


if __name__ == "__main__":
    sys.exit(main())
